permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Otter Pop"
description: "nothing to see here"
base url: ''
highlighter: rouge


#links for the blog tabs
links:
  - title: twitter
    url: http://twitter.com/xyba_gamergirl
    icon: twittericon
  - title: link
    url: links.html
    icon: link
  - title: About
    url: 
    icon: openbookicon
  - title: RainbowsAndSugarPlums
    url: rainbowsandsugarplums.html
    icon: purplebunny456
    